### ISSUE TITLE
Running moclojer as framework it has an error when hit the localhost:8000

### ISSUE THREAD

**Issue by matheusfrancisco** [moclojer/moclojer#201]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

runing as the doc said:
```clojure
(ns example.core
  (:require
   [com.moclojer.adapters :as adapters]
   [com.moclojer.server :as server]))


(def *router
  "create a router from a config map"
  (adapters/generate-routes
   [{:endpoint
     {:method "GET"
      :path "/example"
      :response {:status 200
                 :headers {:Content-Type "application/json"}
                 :body {:id 123}}}}]))


(server/start-server! *router)

```

when i hit the url localhost:8000 it has an error
![image](https://github.com/moclojer/moclojer/assets/6428732/dea576a4-215c-4bfa-8791-6d5f42e8522e)

```
WARNING: /
java.lang.UnsupportedOperationException: Use .getMatched(String) instead
        at org.eclipse.jetty.http.pathmap.PathMappings.getMatch(PathMappings.java:259)
        at org.eclipse.jetty.servlet.ServletHandler.getMappedServlet(ServletHandler.java:572)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:468)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
```
![image](https://github.com/moclojer/moclojer/assets/6428732/4edbce85-cf2c-46d4-93e9-54f898daa394)

### Reproduce the Bug

```clojure
(ns example.core
  (:require
   [com.moclojer.adapters :as adapters]
   [com.moclojer.server :as server]))


(def *router
  "create a router from a config map"
  (adapters/generate-routes
   [{:endpoint
     {:method "GET"
      :path "/example"
      :response {:status 200
                 :headers {:Content-Type "application/json"}
                 :body {:id 123}}}}]))


(server/start-server! *router)

```
and hit the url 

### moclojer config

use has a framework without the yml

### Expected Behavior

return the id 123 when hit the /example

### Version and environment information

Os system: linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by matheusfrancisco** [comment]
#204
